<?php

/**
 * @file
 * Contains relevant_content.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function relevant_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.relevant_content':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Relevant Content') . '</p>';
      return $output;

    break;
  }
}

/**
 * Implements hook_theme().
 */
function relevant_content_theme($existing, $type, $theme, $path) {
  $theme = array(
    'item_list__relevant_content' =>
      array(
        'template' => 'item-list--relevant-content',
      ),
  );
  return $theme;

}
