<?php

/**
 * @file
 * Contains relevant_content.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function relevant_content_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        case 'help.page.relevant_content':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Relevant Content') . '</p>';
            return $output;
            break;
    }
}

/**
 * Implements hook_theme().
 */
function relevant_content_theme($existing, $type, $theme, $path) {
    // Add items variable and assign twig template for the block template.
    return [
        'relevant_content_block' =>
            [
                'attributes' => [
                    'class' => ['relevant-content'],
                ],
                'template' => 'block--relevant-content-block',
            ],
        ];
}
